/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao.filmegenero;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vitoria
 */
public class ConsultarGeneroporFilme extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultarGeneroporFilme.class.getName());

    /**
     * Creates new form ConsultarGeneroporFilme
     */
    public ConsultarGeneroporFilme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFilmeGenero = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIDConsulta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(this::btnConsultarActionPerformed);

        jButton1.setText("Fechar");

        tblFilmeGenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Filme_Genero ", "ID_Genero", "Nome_Genero", "ID_Filme", "Nome_Filme"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFilmeGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFilmeGeneroMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblFilmeGenero);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Consultar Filme_Genero");

        jLabel1.setText("ID_Genero:");

        txtIDConsulta.addActionListener(this::txtIDConsultaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultar)
                                .addGap(87, 87, 87)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtIDConsulta)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(jButton1))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            DefaultTableModel modelo = (DefaultTableModel) tblFilmeGenero.getModel();
            modelo.setNumRows(0);

            controle.Filme_GeneroControle fgc = new controle.Filme_GeneroControle();
            String texto = txtIDConsulta.getText().trim();

            if (texto.isEmpty()) {
                for (modelo.Filme_genero fg : fgc.consultarFilme_genero()) {
                    modelo.addRow(new Object[]{
                        fg.getID_Filme_Genero(),
                        fg.getID_Genero().getID_Genero(),
                        fg.getID_Genero().getNome_genero(),   // nome do gênero
                        fg.getID_Filme().getID_Filme(),
                        fg.getID_Filme().getNome_filme()      // nome do filme
                    });
                }
            } else {
                int id = Integer.parseInt(texto);
                java.util.ArrayList<modelo.Filme_genero> lista = fgc.consultarFIlmeporGenero(id);

                if (!lista.isEmpty()) {
                    for (modelo.Filme_genero fg : lista) {
                        modelo.addRow(new Object[]{
                            fg.getID_Filme_Genero(),
                            fg.getID_Genero().getID_Genero(),
                            fg.getID_Genero().getNome_genero(),
                            fg.getID_Filme().getID_Filme(),
                            fg.getID_Filme().getNome_filme()
                        });
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Nenhum filme encontrado para o ID " + id);
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite apenas números no campo ID.",
                "Entrada inválida", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void tblFilmeGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFilmeGeneroMouseClicked
        if (evt.getClickCount() == 2) {
            int linha = tblFilmeGenero.getSelectedRow();
            if (linha == -1) return;

            AlterarFilmeGenero telaAlt = new AlterarFilmeGenero();
            telaAlt.carregarDados(
                tblFilmeGenero.getValueAt(linha, 0).toString(), // ID_Filme_Genero → spinner
                tblFilmeGenero.getValueAt(linha, 1).toString(), // ID_Genero
                tblFilmeGenero.getValueAt(linha, 3).toString()  // ID_Filme (coluna 3, não 2!)
            );
            telaAlt.setVisible(true);

        }
    }//GEN-LAST:event_tblFilmeGeneroMouseClicked

    private void txtIDConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultarGeneroporFilme().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblFilmeGenero;
    private javax.swing.JTextField txtIDConsulta;
    // End of variables declaration//GEN-END:variables
}
