/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao.elenco;

import controle.ElencoControle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Elenco;



/**
 *
 * @author Débora
 */
public class ConsultarElenco extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultarElenco.class.getName());

    /**
     * Creates new form ConsultarElenco
     */
    public ConsultarElenco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblElenco = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDElenco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        tblElenco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID_Elenco", "nome", "foto_elenco"
            }
        ));
        tblElenco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblElencoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblElenco);

        txtNome.addActionListener(this::txtNomeActionPerformed);

        btnLimpar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(this::btnConsultarActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Consultar Elenco");

        jLabel3.setText("ID Elenco:");

        txtIDElenco.addActionListener(this::txtIDElencoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDElenco)
                            .addComponent(txtNome)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIDElenco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnLimpar))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_btnConsultarActionPerformed

    public void atualizarTabela() {
          ElencoControle ec = new ElencoControle();
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblElenco.getModel();
    modelo.setNumRows(0);

    String textoID = txtIDElenco.getText().trim();
    String textoNome = txtNome.getText().trim();

    // Se digitou um ID, busca por ID
    if (!textoID.isEmpty()) {
        try {
            int id = Integer.parseInt(textoID);
            Elenco e = ec.consultarID_Elenco(id);
            if (e.getNome() != null) {
                modelo.addRow(new Object[]{
                    e.getID_Elenco(),
                    e.getNome(),
                    e.getFoto_elenco()
                });
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Nenhum elenco encontrado com o ID " + id,
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "ID inválido. Digite apenas números.",
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        return;
    }

    // Se digitou um nome, filtra por nome
    if (!textoNome.isEmpty()) {
        ArrayList<Elenco> lista = ec.consultarElenco();
        String nomeBusca = textoNome.toLowerCase();
        for (Elenco e : lista) {
            if (e.getNome() != null && e.getNome().toLowerCase().contains(nomeBusca)) {
                modelo.addRow(new Object[]{
                    e.getID_Elenco(),
                    e.getNome(),
                    e.getFoto_elenco()
                });
            }
        }
        if (modelo.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Nenhum elenco encontrado com o nome \"" + textoNome + "\".",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        return;
    }

    // Se nenhum filtro, mostra todos
    ArrayList<Elenco> todos = ec.consultarElenco();
    for (Elenco e : todos) {
        modelo.addRow(new Object[]{
            e.getID_Elenco(),
            e.getNome(),
            e.getFoto_elenco()
        });
    }
    }

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
         txtIDElenco.setText(""); // era txtIDConsulta
    txtNome.setText("");
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblElenco.getModel();
    modelo.setNumRows(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tblElencoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblElencoMouseClicked
        if (evt.getClickCount() == 2) {
            int linhaSelecionada = tblElenco.getSelectedRow();
            AlterarElenco telaAlt = new AlterarElenco();

            telaAlt.txtIDElenco.setText(tblElenco.getValueAt(linhaSelecionada, 0).toString());
            telaAlt.txtNome.setText(tblElenco.getValueAt(linhaSelecionada, 1).toString());

            telaAlt.setVisible(true);
        }
    }//GEN-LAST:event_tblElencoMouseClicked

    private void txtIDElencoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDElencoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDElencoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultarElenco().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblElenco;
    public javax.swing.JTextField txtIDElenco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

   
}
